Repository causify-ai/helpers, pull requests merged in 2025-04, with the labels that each got.

#469 HelpersTask331_Move_out_code_for_docformatter_testing
  linters/test/outcomes/Test_docformatter.test6/input/test.txt
  linters/test/test_amp_doc_formatter.py
Labels: PR_for_reviewers

#467 HelpersTask301_dot_at_beginning_of_dir_is_removed
  linters/amp_fix_md_links.py
  linters/test/outcomes/Test_fix_links.test1/output/test.txt
  linters/test/test_amp_fix_md_links.py
Labels: PR_for_reviewers

#473 HelpersTask458_Add_docstring_to_hpandas.list_to_str
  helpers/hpandas.py
Labels: PR_for_reviewers

#442 HelpersTask397_Replace_data_with_df_in_hdataframe
  helpers/hdataframe.py
  helpers/test/test_hdataframe.py
Labels: documentation

#478 HelpersTask463_tests_for_increase_chapters
  helpers/test/test_hmarkdown.py
Labels: PR_for_reviewers

#468 HelpersTask388_Sudo_password_requested_running_invoke_on_Linux_locally
  docs/onboarding/intern.set_up_development_on_laptop.how_to_guide.md
Labels: PR_for_reviewers

#477 HelpersTask459_Add_unit_tests_for_hpandas.list_to_str
  helpers/test/test_hpandas.py
Labels: PR_for_reviewers

#489 Use dassert_file_extension to verify extension
  helpers/hpickle.py
Labels: PR_for_reviewers

#486 HelpersTask456_Remove_is_running_on_macos_in_favor_of_is_mac
  helpers/hsystem.py
  helpers/lib_tasks_utils.py
Labels: PR_for_reviewers

#491 HelpersTask408 Rename is_cmamp_prod to is_prod_csfy
  helpers/hserver.py
  helpers/test/test_hserver.py
Labels: PR_for_authors

#490 HelpersTask294_Linter_removed_filename_from_fig_pointer
  linters/amp_fix_md_links.py
  linters/test/test_amp_fix_md_links.py
Labels: PR_for_reviewers

#482 HelpersTask465_generalize_increase_chapter
  dev_scripts_helpers/documentation/transform_notes.py
  helpers/hmarkdown.py
  helpers/test/test_hmarkdown.py
Labels: PR_for_reviewers

#492 Cmamptask11766_Update_the_docs_pushing_images_to_GHCR
  docs/work_tools/all.devops_docker.how_to_guide.md
Labels: PR_for_reviewers

#510 Cmamptask11809_Build_failure_cmamp_Import_cycles_detector_14276183967_11809
  helpers/lib_tasks_lint.py
  helpers/lib_tasks_pytest.py
Labels: PR_for_reviewers

#499 HelpersTask332_factor_out_type_check_in_linter_action
  linters/action.py
  linters/amp_add_class_frames.py
  linters/amp_add_toc_to_notebook.py
  linters/amp_autoflake.py
  linters/amp_black.py
  linters/amp_check_filename.py
  linters/amp_check_import.py
  linters/amp_check_md_reference.py
  linters/amp_check_md_toc_headers.py
  linters/amp_check_shebang.py
  linters/amp_class_method_order.py
  linters/amp_doc_formatter.py
  linters/amp_fix_comments.py
  linters/amp_fix_md_links.py
  linters/amp_flake8.py
  linters/amp_format_separating_line.py
  linters/amp_isort.py
  linters/amp_normalize_import.py
  linters/amp_pylint.py
  linters/amp_warn_incorrectly_formatted_todo.py
Labels: PR_for_reviewers

#498 HelpersTask300_Check_repo_name_before_shortening_links
  helpers/test/test_hgit.py
  linters/amp_fix_md_links.py
  linters/test/test_amp_fix_md_links.py
Labels: PR_for_reviewers

#495 HelpersTask407_Rename__ck_to__csfy
  dev_scripts_helpers/thin_client/build.py
  dev_scripts_helpers/thin_client/thin_client_utils.py
  dev_scripts_helpers/thin_client/thin_client_utils.sh
  helpers/hserver.py
  helpers/hunit_test_utils.py
  helpers/lib_tasks_docker.py
  helpers/lib_tasks_perms.py
  helpers/lib_tasks_pytest.py
  helpers/test/test_hserver.py
  helpers/test/test_lib_tasks_pytest.py
  helpers/test/test_repo_config_amp.py
Labels: PR_for_reviewers

#525 HelpersTask524-clearing-the-confusion-in-thin-envio-setup-guide
  docs/onboarding/intern.set_up_development_on_laptop.how_to_guide.md
Labels: PR_for_authors

#513 HelpersTask333 Convert VeraCrypt doc to Markdown
  docs/work_tools/ck.veracrypt.how_to_guide.md
  docs/work_tools/figs/veracrypt/image1.png
  docs/work_tools/figs/veracrypt/image10.png
  docs/work_tools/figs/veracrypt/image11.png
  docs/work_tools/figs/veracrypt/image12.png
  docs/work_tools/figs/veracrypt/image13.png
  docs/work_tools/figs/veracrypt/image2.png
  docs/work_tools/figs/veracrypt/image3.png
  docs/work_tools/figs/veracrypt/image4.png
  docs/work_tools/figs/veracrypt/image5.png
  docs/work_tools/figs/veracrypt/image6.png
  docs/work_tools/figs/veracrypt/image7.png
  docs/work_tools/figs/veracrypt/image8.png
  docs/work_tools/figs/veracrypt/image9.png
Labels: PR_for_authors

#522 HelpersTask521-running-causify-on-windows-md-guide
  docs/onboarding/intern.running_causify_on_virtual_machine.how_to_guide.md
  docs/onboarding/intern.set_up_development_on_laptop.how_to_guide.md
Labels: PR_for_authors, PR_for_integrators

#556 Cmamptask11656_Post_status_if_was_triggered_manually
  .github/workflows/common_linter.yml
  .github/workflows/common_run_tests.yml
Labels: PR_for_reviewers

#426 CmTask11401_Find_a_way_to_keep_GitHub_repos_in_sync
  dev_scripts_helpers/github/labels/gh_issues_labels.yml
  dev_scripts_helpers/github/sync_gh_issue_labels.py
Labels: PR_for_reviewers

#558 HelpersTask553_Break_in_slow_tests___dockerized_executables
  dev_scripts_helpers/documentation/lint_notes.py
  helpers/hdocker.py
  linters/test/outcomes/Test_linter_py1.test_linter_md1/output/test.txt
Labels: PR for reviewers

#552 HelpersTask464-use-is_header-in-hmarkdown
  helpers/hmarkdown.py
Labels: PR for reviewers

#496 HelpersTask461 Add tests for remove_code_delimiters
  helpers/test/test_hmarkdown.py
Labels: PR for authors

#505 CmampTask11789_Make_cmamp_GitHub_Actions_workflows_reusable
  .github/workflows/common_linter.yml
  .github/workflows/common_run_tests.yml
Labels: PR for reviewers

#555 HelpersTask533 Incorrect header level update after code blocks
  linters/amp_check_md_toc_headers.py
  linters/test/outcomes/Test_fix_md_headers.test2/output/test.txt
  linters/test/test_amp_check_md_toc_headers.py
Labels: PR for authors

#571 CmampTask11895_Build_failure___cmamp___Update_helpers_submodule___14474016777
  helpers/hserver.py
  helpers/hunit_test_utils.py
  helpers/test/test_repo_config_amp.py
Labels: PR for reviewers

#577 HelpersTask576-correct-the-command-in-all.run_unit_tests.how_to_guide
  docs/coding/all.run_unit_tests.how_to_guide.md
Labels: PR for reviewers

#535 HelpersTask445_Fix_bug_in_removed_blocks_storage_linter
  helpers/hstring.py
  helpers/test/outcomes/TestGetDocstrings.test1/input/test.txt
  helpers/test/test_hstring.py
  linters/amp_doc_formatter.py
  linters/test/outcomes/TestFindUnbalancedBackticks.test1/input/test.txt
  linters/test/test_amp_doc_formatter.py
Labels: PR for reviewers

#584 HelpersTask568_moving_line_in_golden_output
  linters/test/outcomes/Test_linter_py1.test_linter_md1/output/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter_md2/output/test.txt
  linters/test/test_amp_dev_scripts.py
Labels: PR for reviewers

#528 HelpersTask334_avoid_empty_lines_in_code
  docs/coding/all.developing_linter.how_to_guide.md
  linters/amp_remove_empty_lines_in_function.py
  linters/base.py
  linters/test/outcomes/Test_linter_py1.test_DevToolsTask408/output/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter1/output/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter2/output/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter_ipynb1/output/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter_md1/output/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter_txt1/output/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter_txt2/output/test.txt
  linters/test/outcomes/Test_remove_empty_lines.test1/input/test.txt
  linters/test/outcomes/Test_remove_empty_lines.test1/output/test.txt
  linters/test/outcomes/Test_remove_empty_lines.test2/input/test.txt
  linters/test/outcomes/Test_remove_empty_lines.test2/output/test.txt
  linters/test/outcomes/Test_remove_empty_lines.test3/input/test.txt
  linters/test/outcomes/Test_remove_empty_lines.test3/output/test.txt
  linters/test/outcomes/Test_remove_empty_lines.test4/input/test.txt
  linters/test/outcomes/Test_remove_empty_lines.test4/output/test.txt
  linters/test/test_amp_remove_empty_lines_in_function.py
Labels: PR for reviewers

#587 HelpersTask585_move_scripts_from_test_to_input_dir
  linters/test/outcomes/Test_linter_py1.test_DevToolsTask408/input/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter1/input/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter2/input/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter_ipynb1/input/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter_md1/input/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter_md2/input/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter_txt1/input/test.txt
  linters/test/outcomes/Test_linter_py1.test_linter_txt2/input/test.txt
  linters/test/test_amp_dev_scripts.py
Labels: PR for reviewers

#592 HelpersTask545 Unstage tmp files added by Linter
  linters/base.py
  linters/utils.py
Labels: PR for authors

#567 HelpersTask282_Rename_DIR_PREFIX_to_DIR_SUFFIX
  dev_scripts_helpers/thin_client/build.py
  dev_scripts_helpers/thin_client/test_super_repo.sh
  dev_scripts_helpers/thin_client/thin_client_utils.py
  dev_scripts_helpers/thin_client/tmux.py
  helpers/repo_config_utils.py
Labels: PR for reviewers

#593 HelpersTask559 Move _load_labels and _save_labels to Label class
  dev_scripts_helpers/github/sync_gh_issue_labels.py
Labels: PR for reviewers

#599 CmampTask11073_Add_pre_commit_hooks_to_scan_for_secrets
  dev_scripts_helpers/git/git_hooks/commit-msg.py
  dev_scripts_helpers/git/git_hooks/install_hooks.py
  dev_scripts_helpers/git/git_hooks/pre-commit.py
  dev_scripts_helpers/git/git_hooks/utils.py
  dev_scripts_helpers/thin_client/setenv.sh
Labels: PR for reviewers

#602 HelpersTask438 Document process on synchronizing GH issue labels
  docs/work_tools/dev_system/all.synchronize_gh_issue_labels.how_to_guide.md
  docs/work_tools/dev_system/figs/synchronize_gh_issue_labels/image1.png
  docs/work_tools/dev_system/figs/synchronize_gh_issue_labels/image2.png
  docs/work_tools/dev_system/figs/synchronize_gh_issue_labels/image3.png
Labels: PR for authors

#600 HelpersTask560_Create_dockerized_executable_for_gh_issue_labels
  dev_scripts_helpers/github/dockerized_sync_gh_issue_labels.py
  dev_scripts_helpers/github/sync_gh_issue_labels.py
Labels: PR for authors

#630 HelpersTask611_Update_doc_new_convention_of_dockerized_executable
  docs/work_tools/docker/all.dockerized_flow.explanation.md
Labels: PR for reviewers

#631 CmampTask11073_Add_pre_commit_hooks_to_scan_for_secrets_2
  dev_scripts_helpers/git/git_hooks/commit-msg.py
  dev_scripts_helpers/thin_client/setenv.sh
  repo_config.yaml
Labels: PR for reviewers

#632 CmampTask11073_Document_git_hooks
  docs/work_tools/git/all.git_hooks.reference.md
Labels: PR for reviewers

#586 HelpersTask339_Develop_the_docker_release_multi_arch_prod_image_invoke_2
  docs/work_tools/all.devops_docker.how_to_guide.md
  helpers/lib_tasks_docker_release.py
  tasks.py
Labels: PR for reviewers
